### ISSUE TITLE
fullWidth prop not working

### ISSUE THREAD

**Issue by hugocostadev** [vtex-apps/slider-layout#42]
**Describe the bug**
The fullWidth prop does not work properly, follow the example below.
There is a "dib" class in a span element that I can't customize because the is not a class handle and the  :first-child is not working either. 

I tried to do this and its not woked: 

``` css 
.slideChildrenContainer--carousel :first-child { 
  width: 100%;
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/20212776/90278261-80976c00-de3d-11ea-939e-ce4c42878452.png)
